
-- POLOS ORRDENADOS POR MARCA ASC Y PRECIO DESCENDENTE.
SELECT * FROM polos ORDER BY marca ASC, precio DESC;

-- POLOS DE CHOCOLATE DE MARCAS QUE EMPIECEN POR F CON PRECIOS ENTRE 1 Y 3 EUROS INCLUIDOS
SELECT * FROM polos WHERE LOWER(sabor) LIKE '%chocolate%' AND precio <= 3 AND precio >=1 AND LOWER(MARCA) LIKE 'f%';

--POLOS DE LOS QUE NO SE HAN INDICADO SABOR.
SELECT * FROM polos WHERE sabor IS NULL OR sabor = '';

--MARCA CON 2 O MAS POLOS.
SELECT marca FROM polos GROUP BY marca HAVING COUNT(marca) >= 2;